### ISSUE TITLE
Trying to parse NoneType on a noPage response?

### ISSUE THREAD

**Issue by mnot** [dustin/twitty-twister#4]
I'm getting this sometimes:

Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/twisted/web/client.py", line 143, in handleResponse
    self.status, self.message, response)))
  File "/usr/lib64/python2.6/site-packages/twisted/web/client.py", line 309, in noPage
    self.deferred.errback(reason)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 269, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 312, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib64/python2.6/site-packages/twisted/internet/defer.py", line 328, in _runCallbacks
    self.result = callback(self.result, _args, *_kw)
  File "/usr/lib/python2.6/site-packages/twittytwister/twitter.py", line 306, in <lambda>
    hdef.addCallback(lambda p: deferred.callback(parser(p)))
  File "/usr/lib/python2.6/site-packages/twittytwister/txml.py", line 353, in parseUpdateResponse
    return parseXML(xml).getElementsByTagName("id")[0].firstChild().data
  File "/usr/lib/python2.6/site-packages/twittytwister/txml.py", line 350, in parseXML
    return microdom.parseXMLString(xml)
  File "/usr/lib64/python2.6/site-packages/twisted/web/microdom.py", line 888, in parseXMLString
    return parseString(st, caseInsensitive=0, preserveCase=1)
  File "/usr/lib64/python2.6/site-packages/twisted/web/microdom.py", line 878, in parseString
    return parse(StringIO(st), _args, *_kw)
exceptions.TypeError: expected read buffer, NoneType found

**Comment by akrherz** [comment]
Hi mnot, I am seeing this too.  Did you resolve it?

**Comment by mnot** [comment]
Nope.
